<?php

namespace App\Imports;

use App\Models\Households;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Validators\Failure;
use Maatwebsite\Excel\Concerns\Importable;
use Maatwebsite\Excel\Concerns\SkipsOnFailure;
use Maatwebsite\Excel\Concerns\WithValidation;
use Maatwebsite\Excel\Concerns\SkipsFailures;
use Maatwebsite\Excel\Concerns\WithStartRow;
use Carbon\Carbon;
use Maatwebsite\Excel\Concerns\SkipsErrors;
use Maatwebsite\Excel\Concerns\SkipsOnError;
use PhpOffice\PhpSpreadsheet\Shared\Date;
use Throwable;
use Maatwebsite\Excel\Concerns\SkipsEmptyRows;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithHeadings;

class HouseholdsImport implements ToModel, WithStartRow,WithValidation,SkipsEmptyRows
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    use Importable, SkipsFailures;
    private $rowCount = -1;
    public function model(array $row)
    {
        $this->rowCount++;
        return new Households([
           'housecontrolnum'=>$row[1],
           'headname'=>$row[2],
           'watersupply'=>$row[3],
           'waternum'=>$row[4],
           'toilettype'=>$row[5],
           'tenure'=>$row[6],
           'rentpm'=>$row[7],
           'fuel'=>$row[8],
           'electric'=>$row[9],
           'electricsrc'=>$row[10],
           'generator'=>$row[11],
           'solar'=>$row[12],
           'battery'=>$row[13],
           'electrico'=>$row[14],
           'landagri'=>$row[15],
           'landagrinum'=>$row[16],
           'landres'=>$row[17],
           'landresum'=>$row[18],
           'landcom'=>$row[19],
           'landcomnum'=>$row[20],
           'car'=>$row[21],
           'carnum'=>$row[22],
           'tricycle'=>$row[23],
           'trciyclenum'=>$row[24],
           'bicycle'=>$row[25],
           'bicyclenum'=>$row[26],
           'pedi'=>$row[27],
           'pedinum'=>$row[28],
           'tv'=>$row[29],
           'tvnum'=>$row[30],
           'dvd'=>$row[31],
           'dvdnum'=>$row[32],
           'casette'=>$row[33],
           'casettenum'=>$row[34],
           'karaoke'=>$row[35],
           'karaokenum'=>$row[36],
           'cell'=>$row[37],
           'cellnum'=>$row[38],
           'tel'=>$row[39],
           'telnum'=>$row[40],
           'comp'=>$row[41],
           'compnum'=>$row[42],
           'fan'=>$row[43],
           'fannum'=>$row[44],
           'aircon'=>$row[45],
           'airconum'=>$row[46],
           'iron'=>$row[47],
           'ironnum'=>$row[48],
           'washing'=>$row[49],
           'washingnum'=>$row[50],
           'ref'=>$row[51],
           'refnum'=>$row[52],
           'stove'=>$row[53],
           'stovenum'=>$row[54],
           'rice'=>$row[55],
           'ricenum'=>$row[56],
           'oven'=>$row[57],
           'ovennum'=>$row[58],
           'toaster'=>$row[59],
           'toasternum'=>$row[60],
           'dispenser'=>$row[61],
           'dispensernum'=>$row[62],
           'sala'=>$row[63],
           'salanum'=>$row[64],
           'mats'=>$row[65],
           'matsnum'=>$row[66],
           'folding'=>$row[67],
           'foldingnum'=>$row[68],
           'sofa'=>$row[69],
           'sofanum'=>$row[70],
           'othersname'=>$row[71],
           'othersnum'=>$row[72],
           'internet'=>$row[73],
           'house'=>$row[74],
           'houseinsurance'=>$row[75],
           'motor'=>$row[76],
           'motorinsurance'=>$row[77],
           'app'=>$row[78],
           'appinsurance'=>$row[79],
           'gcollection'=>$row[80],
           'burn'=>$row[81],
           'compost'=>$row[82],
           'recycle'=>$row[83],
           'waste'=>$row[84],
           'pitw'=>$row[85],
           'pitwo'=>$row[86],
           'throwing'=>$row[87],
           'gothers'=>$row[88],
           'gcollect'=>$row[89],
           'gnum'=>$row[90],
           'crop'=>$row[91],
           'cropcash'=>$row[92],
           'cropkind'=>$row[93],
           'livestock'=>$row[94],
           'livecash'=>$row[95],
           'livekind'=>$row[96],
           'fishing'=>$row[97],
           'fishcash'=>$row[98],
           'fishkind'=>$row[99],
           'forestry'=>$row[100],
           'forestycash'=>$row[101],
           'forestykind'=>$row[102],
           'wholesale'=>$row[103],
           'wholesalecash'=>$row[104],
           'wholesalekind'=>$row[105],
           'manufacturing'=>$row[106],
           'manucash'=>$row[107],
           'manukind'=>$row[108],
           'community'=>$row[109],
           'servcash'=>$row[110],
           'servkind'=>$row[111],
           'storage'=>$row[112],
           'transpocash'=>$row[113],
           'transpokind'=>$row[114],
           'mining'=>$row[115],
           'miningcash'=>$row[116],
           'miningkind'=>$row[117],
           'construct'=>$row[118],
           'constcash'=>$row[119],
           'constkind'=>$row[120],
           'elsewhere'=>$row[121],
           'actcash'=>$row[122],
           'actkind'=>$row[123],
           'totalnetincomecash'=>$row[124],
           'totalneticomekind'=>$row[125],
           'totalsalarykind'=>$row[126],
           'totalsalarycash'=>$row[127],
           'ofwcash'=>$row[128],
           'ofwkind'=>$row[129],
           'abroadcash'=>$row[130],
           'abroadkind'=>$row[131],
           'domesticcash'=>$row[132],
           'domestickind'=>$row[133],
           'pensioncash'=>$row[134],
           'pensionkind'=>$row[135],
           'netsharecash'=>$row[136],
           'netsharekind'=>$row[137],
           'rentalscash'=>$row[138],
           'rentalskind'=>$row[139],
           'interestcash'=>$row[140],
           'interestkind'=>$row[141],
           'investcash'=>$row[142],
           'investkind'=>$row[143],
           'sourcecash'=>$row[144],
           'sourcekind'=>$row[145],
           'totalgrosscash'=>$row[146],
           'totalgrosskind'=>$row[147],
           'totalimputed'=>$row[148],
           'totalcash'=>$row[149],
           'totalkind'=>$row[150],
           'totalincome'=>$row[151],
           'tenurestatus'=>$row[152],
           'agrilandnum'=>$row[153],
           'tempcrops'=>$row[154],
           'tempcropskilo'=>$row[155],
           'permacrops'=>$row[156],
           'permaccropskilo'=>$row[157],
           'tcrops'=>$row[158],
           'tcropskilo'=>$row[159],
           'pcrops'=>$row[160],
           'pcropskilo'=>$row[161],
           'hcrops'=>$row[162],
           'hcropskilo'=>$row[163],
           'beastnum'=>$row[164],
           'beastown'=>$row[165],
           'plownum'=>$row[166],
           'plowown'=>$row[167],
           'harrownum'=>$row[168],
           'harrowown'=>$row[169],
           'mowernum'=>$row[170],
           'mowerown'=>$row[171],
           'cornnum'=>$row[172],
           'cornown'=>$row[173],
           'spraynum'=>$row[174],
           'sprayown'=>$row[175],
           'tractornum'=>$row[176],
           'tractorown'=>$row[177],
           'htractornum'=>$row[178],
           'htractorown'=>$row[179],
           'turtlenum'=>$row[180],
           'turtleown'=>$row[181],
           'planternum'=>$row[182],
           'planterown'=>$row[183],
           'dryernum'=>$row[184],
           'dryeown'=>$row[185],
           'mdrynum'=>$row[186],
           'mdryown'=>$row[187],
           'millnum'=>$row[188],
           'millown'=>$row[189],
           'harvesternum'=>$row[190],
           'harvesterown'=>$row[191],
           'granarynum'=>$row[192],
           'granaryown'=>$row[193],
           'shednum'=>$row[194],
           'shedown'=>$row[195],
           'pumpnum'=>$row[196],
           'pumpown'=>$row[197],
           'agriequip'=>$row[198],
           'agriequipnum'=>$row[199],
           'animals'=>$row[200],
           'animalssold'=>$row[201],
           'animalsconsume'=>$row[202],
           'meat'=>$row[203],
           'meatsold'=>$row[204],
           'meatconsume'=>$row[205],
           'milk'=>$row[206],
           'milksold'=>$row[207],
           'milkconsume'=>$row[208],
           'eggs'=>$row[209],
           'eggsold'=>$row[210],
           'eggconsume'=>$row[211],
           'otherlivestock'=>$row[212],
           'otherlivestocksold'=>$row[213],
           'otherlivestockconsume'=>$row[214],
           'catching'=>$row[215],
           'culturing'=>$row[216],
           'fishloc'=>$row[217],
           'boatone'=>$row[218],
           'boatoneown'=>$row[219],
           'boattwo'=>$row[220],
           'boattwoown'=>$row[221],
           'boatthree'=>$row[222],
           'boathreeown'=>$row[223],
           'boatfour'=>$row[224],
           'boatfourown'=>$row[225],
           'boatfive'=>$row[226],
           'boatfiveown'=>$row[227],
           'gearone'=>$row[228],
           'gearoneown'=>$row[229],
           'geartwo'=>$row[230],
           'geartwoown'=>$row[231],
           'gearthree'=>$row[232],
           'gearthreeown'=>$row[233],
           'gearfour'=>$row[234],
           'gearfourown'=>$row[235],
           'pond'=>$row[236],
           'fishp'=>$row[237],
           'fishc'=>$row[238],
           'seaweed'=>$row[239],
           'oyster'=>$row[240],
           'mussel'=>$row[241],
           'fisht'=>$row[242],
           'hatchery'=>$row[243],
           'aquaot'=>$row[244],
           'fishone'=>$row[245],
           'fishoneown'=>$row[246],
           'fishtwo'=>$row[247],
           'fishtwoown'=>$row[248],
           'fishthree'=>$row[249],
           'fishthreeown'=>$row[250],
           'fishfour'=>$row[251],
           'fishfourown'=>$row[252],
           'fishfive'=>$row[253],
           'fishfiveown'=>$row[254],
           'livingnum'=>$row[255],
           'harvestyrs'=>$row[256],
           'harvestr'=>$row[257],
           'harvestpr'=>$row[258],
           'samecrop'=>$row[259],
           'samecropr'=>$row[260],
           'difcrop'=>$row[261],
           'difcropr'=>$row[262],
           'cropi'=>$row[263],
           'cropiprov'=>$row[264],
           'agrif'=>$row[265],
           'agrifprov'=>$row[266],
           'livestocknum'=>$row[267],
           'livestockc'=>$row[268],
           'livestockr'=>$row[269],
           'livestocki'=>$row[270],
           'livestockip'=>$row[271],
           'fishyrs'=>$row[272],
           'fishyrsc'=>$row[273],
           'fishr'=>$row[274],
           'fishi'=>$row[275],
           'fiship'=>$row[276],
           'temp'=>$row[277],
           'brownout'=>$row[278],
           'sealevel'=>$row[279],
           'water'=>$row[280],
           'waterr'=>$row[281],
           'floodt'=>$row[282],
           'floodhrs'=>$row[283],
           'floodmnths'=>$row[284],
           'drought'=>$row[285],
           'droughtnum'=>$row[286],
           'moveout'=>$row[287],
           'moveoutr'=>$row[288],
           'evacuate'=>$row[289],
           'evacuateloc'=>$row[290],
           'evacuatenum'=>$row[291],
           'typhoon'=>$row[292],
           'typhoonnum'=>$row[293],
           'typhoona'=>$row[294],
           'typhoonsrc'=>$row[295],
           'flood'=>$row[296],
           'floodnum'=>$row[297],
           'flooda'=>$row[298],
           'floodsrc'=>$row[299],
           'drough'=>$row[300],
           'droughnum'=>$row[301],
           'droughta'=>$row[302],
           'droughtsrc'=>$row[303],
           'quake'=>$row[304],
           'quakenum'=>$row[305],
           'quakea'=>$row[306],
           'quakesrc'=>$row[307],
           'erupt'=>$row[308],
           'eruptnum'=>$row[309],
           'erupta'=>$row[310],
           'eruptsrc'=>$row[311],
           'landslide'=>$row[312],
           'landslidenum'=>$row[313],
           'landslinea'=>$row[314],
           'landslinesrc'=>$row[315],
           'tsunami'=>$row[316],
           'tsunaminum'=>$row[317],
           'tsunamia'=>$row[318],
           'tsunamisrc'=>$row[319],
           'fire'=>$row[320],
           'firenum'=>$row[321],
           'firea'=>$row[322],
           'firesrc'=>$row[323],
           'forest'=>$row[324],
           'forestnum'=>$row[325],
           'foresta'=>$row[326],
           'forestsrc'=>$row[327],
           'conflict'=>$row[328],
           'conflictnum'=>$row[329],
           'conflicta'=>$row[330],
           'conflictsrc'=>$row[331],
           'osname'=>$row[332],
           'osnum'=>$row[333],
           'osa'=>$row[334],
           'osasrc'=>$row[335],
           'hungerhappen'=>$row[336],
           'nhunger'=>$row[337],
           'mhunger'=>$row[338],
           'nhungers'=>$row[339],
           'mhungers'=>$row[340],
           'nhungert'=>$row[341],
           'mhungert'=>$row[342],
           'disasterprepaidnesskit'=>$row[343],
           'watery'=>$row[344],
           'waterynum'=>$row[345],
           'food'=>$row[346],
           'foodnum'=>$row[347],
           'match'=>$row[348],
           'matchnum'=>$row[349],
           'light'=>$row[350],
           'lightnum'=>$row[351],
           'radio'=>$row[352],
           'radionum'=>$row[353],
           'candle'=>$row[354],
           'candlenum'=>$row[355],
           'kit'=>$row[356],
           'kitnum'=>$row[357],
           'whistle'=>$row[358],
           'whistlenum'=>$row[359],
           'clothe'=>$row[360],
           'clothenum'=>$row[361],
           'blanket'=>$row[362],
           'blanketnum'=>$row[363],
           'batt'=>$row[364],
           'battnum'=>$row[365],
           'docu'=>$row[366],
           'docunum'=>$row[367],
           'othr'=>$row[368],
           'othrnum'=>$row[369],
           'deathhousehold'=>$row[370],
           'deatho'=>$row[371],
           'deathosex'=>$row[372],
           'deathotime'=>$row[373],
           'deathocause'=>$row[374],
           'deatht'=>$row[375],
           'deathtsex'=>$row[376],
           'deathttime'=>$row[377],
           'deathtcause'=>$row[378],
           'deathth'=>$row[379],
           'deaththsex'=>$row[380],
           'deaththtime'=>$row[381],
           'deatthcause'=>$row[382],

           'slp'=>$row[383],
           'slpname'=>$row[384],
           'memo'=>$row[385],
           'memop'=>$row[386],
           'memoi'=>$row[387],

           'ffw'=>$row[388],
           'ffwname'=>$row[389],
           'memtw'=>$row[390],
           'memtwp'=>$row[391],
           'memtwpi'=>$row[392],


           'cfw'=>$row[393],
           'cfwname'=>$row[394],
           'memth'=>$row[395],
           'memthp'=>$row[396],
           'memthpi'=>$row[397],

           'pension'=>$row[398],
           'pensionaname'=>$row[399],
           'memf'=>$row[400],
           'memfp'=>$row[401],
           'memfpi'=>$row[402],

           'ppp'=>$row[403],
           'pppname'=>$row[404],
           'memfiv'=>$row[405],
           'memfip'=>$row[406],
           'memfipi'=>$row[407],

           'arcdp'=>$row[408],
           'arcdpname'=>$row[409],
           'mems'=>$row[410],
           'memsp'=>$row[411],
           'memspi'=>$row[412],


           'twsp'=>$row[413],
           'twspname'=>$row[414],
           'memse'=>$row[415],
           'memsep'=>$row[416],
           'memsepi'=>$row[417],

           'cbep'=>$row[418],
           'cbepname'=>$row[419],
           'meme'=>$row[420],
           'memep'=>$row[421],
           'memepi'=>$row[422],
           'ohi'=>$row[423],
           'ohiname'=>$row[424],
           'memn'=>$row[425],
           'memnp'=>$row[426],
           'memnpi'=>$row[427],
           'othi'=>$row[428],
           'memnt'=>$row[429],
           'memntp'=>$row[430],
           'memntpi'=>$row[431],

           'health'=>$row[432],
           'healthname'=>$row[433],
           'memte'=>$row[434],
           'memtep'=>$row[435],
           'memtepi'=>$row[436],
           'namehealth'=>$row[437],
           'memten'=>$row[438],

           'memtenp'=>$row[439],

           'memtenpi'=>$row[440],



           'feeding'=>$row[441],
           'feedingname'=>$row[442],
           'memel'=>$row[443],
           'memelp'=>$row[444],
           'memelpi'=>$row[445],
           'namefeeding'=>$row[446],
           'memele'=>$row[447],
           'memelep'=>$row[448],
           'memelepi'=>$row[449],


           'scholar'=>$row[450],
           'namescholar'=>$row[451],
           'memtwe'=>$row[452],
           'memtwep'=>$row[453],
           'memtwepi'=>$row[454],
           'scholarname'=>$row[455],
           'memtwel'=>$row[456],

           'memtwelp'=>$row[457],

           'memtwelpi'=>$row[458],



           'sltrp'=>$row[459],
           'sltrpname'=>$row[460],
           'memthr'=>$row[461],
           'memthrp'=>$row[462],
           'memthrpi'=>$row[463],
           'namesltrp'=>$row[464],
           'memthri'=>$row[465],
           'memthrip'=>$row[466],
           'memthripi'=>$row[467],


           'credit'=>$row[468],
           'namecredit'=>$row[469],
           'memfou'=>$row[470],
           'memfoup'=>$row[471],
           'memfoupi'=>$row[472],
           'creditname'=>$row[473],
           'memfour'=>$row[474],

           'memfourp'=>$row[475],

           'memfourpi'=>$row[476],



           'housing'=>$row[477],
           'housingname'=>$row[478],
           'memfi'=>$row[479],
           'memfifp'=>$row[480],
           'memfifpi'=>$row[481],
           'namehousing'=>$row[482],
           'memfif'=>$row[483],

           'memfiftp'=>$row[484],

           'memfiftpi'=>$row[485],

           'programname'=>$row[486],
           'memsix'=>$row[487],
           'memsixp'=>$row[488],
           'memsixpi'=>$row[489],
           'nameprogram'=>$row[490],
           'memsixt'=>$row[491],
           'memsixtp'=>$row[492],
           'memsixtpi'=>$row[493],
           'programoname'=>$row[494],





           'memsixte'=>$row[495],


           'memsixtep'=>$row[496],



           'memsixtepi'=>$row[497],

        ]);
        
    }
    public function startRow(): int
    {
        return 2;
    }
    public function rules(): array
    {
        return [
            '*.1' => 'required',
            '*.2' => 'required'
           
        
        ];
    }
    public function customValidationMessages()
    {
        return [
            '1' => 'House Control Number field is required',
            '2' => 'Household Head Name field is required'
            
            
        ];
    }

    public function getRowCount(): int
    {
        return $this->rowCount;
    }

}
